version: "3.9"
services:
  chatgpt-next-caigo: 
    container_name: chatgpt-next-caigo
    image: c221b531481b
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /docker/volumes/nginx/conf:/www/server/nginx/conf/nginx.conf  #其他配置文件目录挂载
      - /docker/volumes/nginx/dhparam:/etc/nginx/dhparam
      - /docker/volumes/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- /docker/volumes/nginx/log:/var/log/nginx #日志文件挂载
    environment:
      - VIRTUAL_HOST=ai.caigochat.top
      - VIRTUAL_PORT=3000
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
      - OPENAI_SB=$OPENAI_SB